### ISSUE TITLE
regexplain Deleted Multiple R Packages

### ISSUE THREAD

**Issue by nicholasviau** [gadenbuie/regexplain#17]
After installing regexplain the following packages were deleted from my machine:

- rlang
- yaml
- Rcpp
- tidyselect
- stringi

Very odd behavior.

**Comment by gadenbuie** [comment]
When you say “deleted”, how did you verify that they were removed from your system? Can you show the output from this command? Can you also run `devtools::session_info()` and paste the output here?

**Comment by gadenbuie** [comment]
I'm sorry about the hassle this created!

My guess, from [this comment](https://github.com/rstudio/radix/issues/47#issuecomment-428903943), is that maybe digest was in use during the installation but also was out-of-date on your system so `devtools::install_github()` updated digest package but later installations failed because digest was needed and the package database was corrupt, resulting in the packages going missing? I'm not really sure because I don't import digest so it would have to be that one of the regexplain dependencies depends on digest and both were out of date.

All of this to say I don't think this is directly an issue within `regexplain`, but I am going to update the documentation to recommend that it be installed with the `upgrade = FALSE` flag:

```r
devtools::install_github("gadenbuie/regexplain", upgrade = FALSE)
```

I actually would recommend this in general for installing packages via GitHub. The default behavior for `install_github()` is to update all out-of-date packages, and for a package like this one where I haven't ~wasted too much time~ focused on optimizing for reducing system dependencies this can lead to unexpected things. It's also a good idea to install packages in clean sessions, or to restart your R session before and after installation. This may or may not have helped in this case.

If you happen to have the console output from when you tried to install and can paste it here, that would be super helpful.

**Comment by nicholasviau** [comment]
I can go back next week and check the history logs (not in the office until then). 

I agree that it was likely a quirk on my end and not an underlying issue with `regexplain`. I was a bit stressed at the time and just thought "Go to GitHub and document!"

Great RStudio addin, by the way.

**Comment by gadenbuie** [comment]
I totally understand and thanks!
